# Generated by Django 3.1.1 on 2020-09-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocerystaples',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='householditems',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='personalcare',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='snacksbeverages',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vegetablefruits',
            old_name='type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='grocerystaples',
            name='quantity',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='householditems',
            name='quantity',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='personalcare',
            name='quantity',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='snacksbeverages',
            name='quantity',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='vegetablefruits',
            name='quantity',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
