# Generated by Django 3.1.1 on 2020-09-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200922_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseholdItems',
            new_name='GroceryStaple',
        ),
        migrations.RenameModel(
            old_name='GroceryStaples',
            new_name='HouseholdItem',
        ),
        migrations.RenameModel(
            old_name='VegetableFruits',
            new_name='SnacksBeverage',
        ),
        migrations.RenameModel(
            old_name='SnacksBeverages',
            new_name='VegetableFruit',
        ),
    ]
